/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.ObraDTO;
import excepciones.AdmMaterialesException;
import exception.PresentacionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alega
 */
public class ActividadesForm extends javax.swing.JFrame {
    
    private CoordinadorAplicacion coordinador;
    private CoordinadorNegocio coordinadorNegocio;


    /**
     * Creates new form ActividadesRealizadasForm
     * @param coordinador
     */
    public ActividadesForm(CoordinadorAplicacion coordinador) {
        initComponents();
        getContentPane().setBackground(java.awt.Color.WHITE);
        this.setLocationRelativeTo(null);
        this.coordinador = coordinador;
        this.coordinadorNegocio = CoordinadorNegocio.getInstance();
        ObraDTO obra = this.coordinadorNegocio.obtenerObraSeleccionada();
        campoNombreObra.setText(obra.getDireccion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreEmpresa = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        registrarAct = new javax.swing.JLabel();
        btnAgregarActividad = new javax.swing.JButton();
        campoActividad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        campoNombreObra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 204));
        setResizable(false);

        nombreEmpresa.setText("BuildControl");
        nombreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N

        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBackground(new java.awt.Color(95, 168, 211));
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAtras.setText("Atrás");
        btnAtras.setBackground(new java.awt.Color(95, 168, 211));
        btnAtras.setBorderPainted(false);
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        registrarAct.setText("Registrar actividades");
        registrarAct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAgregarActividad.setText("Agregar actividad");
        btnAgregarActividad.setBackground(new java.awt.Color(95, 168, 211));
        btnAgregarActividad.setBorderPainted(false);
        btnAgregarActividad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarActividad.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActividadActionPerformed(evt);
            }
        });

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        jScrollPane1.setViewportView(campoDescripcion);

        campoNombreObra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNombreObra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        campoNombreObra.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registrarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarActividad)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoNombreObra, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEmpresa)
                    .addComponent(campoNombreObra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrarAct)
                .addGap(34, 34, 34)
                .addComponent(campoActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnAgregarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            siguiente();
        } catch (PresentacionException ex) {
            Logger.getLogger(ActividadesForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AdmMaterialesException ex) {
            Logger.getLogger(ActividadesForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        atras();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAgregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActividadActionPerformed
        agregarActividad();
    }//GEN-LAST:event_btnAgregarActividadActionPerformed

    private void agregarActividad() {
        String titulo = campoActividad.getText().trim();
        String descripcion = campoDescripcion.getText().trim();
        
        try {
            coordinadorNegocio.registrarActividad(titulo, descripcion);
            
            campoActividad.setText("");
            campoDescripcion.setText("");
            
            JOptionPane.showMessageDialog(this, "Actividad agregada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);   
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }

    private void registrarActividades() {
        try {
            coordinadorNegocio.registrarActividades();
            JOptionPane.showMessageDialog(this, "Actividades registradas exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void siguiente() throws PresentacionException, AdmMaterialesException {
        // Validar que se hayan registrado actividades
        if (coordinadorNegocio.obtenerActividades().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe registrar al menos una actividad antes de continuar",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            registrarActividades();
        }
        this.dispose();
        coordinador.mostrarMateriales();
    }
    
    private void atras() {
        // Si se registró al menos una actividad
        if (!coordinadorNegocio.obtenerActividades().isEmpty()) {
            int opcion = JOptionPane.showConfirmDialog(this,
                    "Si retrocede se perderá todo el proceso, ¿seguro que desea continuar?",
                    "Confirmar salida", JOptionPane.YES_NO_OPTION);

            if (opcion != JOptionPane.YES_OPTION) {
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Proceso cancelado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);   
            }
            
            // Limpiar la lista de actividades
            coordinadorNegocio.cancelarActividades();
            coordinadorNegocio.reset();
        }
        this.dispose();
        coordinador.reset();
        coordinador.mostrarObraSeleccionada();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarActividad;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField campoActividad;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoNombreObra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JLabel registrarAct;
    // End of variables declaration//GEN-END:variables
}
