/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import com.github.lgooddatepicker.components.TimePicker;
import dto.AsistenciaPersonalDTO;
import exception.PresentacionException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import utilities.Utilities;

/**
 *
 * @author alega
 */
public class PersonalForm extends JFrame {
    private JPanel panelContenedor;  // Panel donde se agregarán los trabajadores
    private JScrollPane scrollPanel; // Panel con barra de desplazamiento
    private List<String> trabajadores; // Lista de trabajadores
    
    private CoordinadorAplicacion coordinador;
    private CoordinadorNegocio coordinadorNegocio;
    
    private static final Logger logger = Logger.getLogger(PersonalForm.class.getName());
    
    /**
     * Creates new form AsistenciaForm
     * @param coordinador
     */
    public PersonalForm(CoordinadorAplicacion coordinador) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        this.coordinador = coordinador;
        this.coordinadorNegocio = CoordinadorNegocio.getInstance();
        
        // Inicializar lista de trabajadores
        trabajadores = coordinadorNegocio.obtenerPersonal();
        crearPanelAsistencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        timePicker4 = new com.github.lgooddatepicker.components.TimePicker();
        timePicker5 = new com.github.lgooddatepicker.components.TimePicker();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        nombreEmpresa = new javax.swing.JLabel();
        registrarAsistencia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtFiltroPersonal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("Entrada");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Salida");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Notas");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnAtras.setText("Atrás");
        btnAtras.setBackground(new java.awt.Color(95, 168, 211));
        btnAtras.setBorderPainted(false);
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Registrar bitácora");
        btnSiguiente.setBackground(new java.awt.Color(95, 168, 211));
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nombreEmpresa.setText("BuildControl");
        nombreEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N

        registrarAsistencia.setText("Registrar asistencia");
        registrarAsistencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreEmpresa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarAsistencia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtFiltroPersonal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFiltroPersonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroPersonalKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Filtrar por nombre de personal:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtFiltroPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltroPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelPrincipal.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguiente)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        atras();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        siguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void txtFiltroPersonalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroPersonalKeyReleased
        filtrarPersonal();
    }//GEN-LAST:event_txtFiltroPersonalKeyReleased

    private void crearPanelAsistencia() {
        // Crear el panel contenedor con BoxLayout (apilado vertical)
        panelContenedor = new JPanel();
        panelContenedor.setLayout(new BoxLayout(panelContenedor, BoxLayout.Y_AXIS));
        panelContenedor.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Margen
        panelContenedor.setPreferredSize(new Dimension(750, trabajadores.size() * 60)); // Tamaño para el scroll
        panelContenedor.setBackground(Color.WHITE);

        // Llenar el panel con los trabajadores
        agregarPanelesPersonal();

        // Agregar el panel a un JScrollPane
        scrollPanel = new JScrollPane(panelContenedor);
        scrollPanel.setBackground(Color.WHITE);
        scrollPanel.setBorder(null);
        scrollPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED); // Solo mostrar cuando sea necesario
        scrollPanel.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER); // Deshabilitar scroll horizontal
        scrollPanel.getVerticalScrollBar().setUnitIncrement(16); // Suavizar el scroll

        // Agregar el JScrollPane al JFrame
        setLayout(new BorderLayout());
        panelPrincipal.add(scrollPanel, BorderLayout.CENTER);

        setVisible(true);
    }

    // Método principal para agregar los paneles de cada trabajador
    private void agregarPanelesPersonal() {
        Font fuentePanelTrabajador = new Font("Segoe UI", Font.PLAIN, 14);

        for (String trabajador : trabajadores) {
            JPanel panelTrabajador = crearPanelPorPersonal(trabajador);
            Utilities.cambiarFuente(panelTrabajador, fuentePanelTrabajador);
            panelContenedor.add(panelTrabajador);
            panelContenedor.add(Box.createVerticalStrut(10)); // Espacio entre paneles
        }

        actualizarInterfaz();
    }

    private JPanel crearPanelPorPersonal(String trabajador) {
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBackground(Color.WHITE);
        panel.setPreferredSize(new Dimension(750, 60)); // Tamaño uniforme para el panel del trabajador

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 10, 5, 10); // Espaciado alrededor de los componentes (top, left, bottom, right)

        // Crear los componentes
        JCheckBox checkbox = crearCheckBox(trabajador);
        TimePicker timePickerEntrada = crearTimePicker("timePickerEntrada");
        TimePicker timePickerSalida = crearTimePicker("timePickerSalida");
        JTextPane textPaneNotas = crearTextPane("textPaneNotas");

        JLabel lbEntrada = new JLabel("Entrada:");
        JLabel lbSalida = new JLabel("Salida:");
        JLabel lbNotas = new JLabel("Notas:");

        // Para el checkbox, configuramos sin centrado, en la primera celda (columna 0)
        gbc.gridx = 0;
        panel.add(checkbox, gbc);

        // Para las etiquetas, también alineadas a la izquierda
        gbc.gridx = 1;
        panel.add(lbEntrada, gbc);

        gbc.gridx = 2;
        panel.add(timePickerEntrada, gbc);

        gbc.gridx = 3;
        panel.add(lbSalida, gbc);

        gbc.gridx = 4;
        panel.add(timePickerSalida, gbc);

        gbc.gridx = 5;
        panel.add(lbNotas, gbc);

        gbc.gridx = 6;
        panel.add(textPaneNotas, gbc);

        // Inicialmente, ocultar todos los componentes menos el checkbox
        lbEntrada.setVisible(false);
        lbSalida.setVisible(false);
        lbNotas.setVisible(false);
        timePickerEntrada.setVisible(false);
        timePickerSalida.setVisible(false);
        textPaneNotas.setVisible(false);

        // Controlar la visibilidad de los componentes según el estado del checkbox
        checkbox.addActionListener(e -> panelComponentesVisibilidad(checkbox, lbEntrada, lbSalida, lbNotas, timePickerEntrada, timePickerSalida, textPaneNotas));

        return panel;
    }

// Crear un JCheckBox con nombre
    private JCheckBox crearCheckBox(String texto) {
        JCheckBox checkbox = new JCheckBox(texto);
        checkbox.setBackground(Color.WHITE);
        checkbox.setName("checkbox");
        return checkbox;
    }

// Crear un TimePicker con nombre
    private TimePicker crearTimePicker(String nombre) {
        TimePicker timePicker = new TimePicker();
        timePicker.setName(nombre);
        return timePicker;
    }

    // Crear un JTextPane con nombre
    private JTextPane crearTextPane(String nombre) {
        JTextPane textPane = new JTextPane();
        textPane.setPreferredSize(new Dimension(150, 25));
        textPane.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        textPane.setName(nombre);
        
        return textPane;
    }

    // Controlar la visibilidad de los componentes según el checkbox
    private void panelComponentesVisibilidad(JCheckBox checkbox, JLabel lbEntrada, JLabel lbSalida, JLabel lbNotas, TimePicker timePickerEntrada, TimePicker timePickerSalida, JTextPane textPaneNotas) {
        boolean seleccionado = checkbox.isSelected();
        
        lbEntrada.setVisible(seleccionado);
        lbSalida.setVisible(seleccionado);
        lbNotas.setVisible(seleccionado);
        timePickerEntrada.setVisible(seleccionado);
        timePickerSalida.setVisible(seleccionado);
        textPaneNotas.setVisible(seleccionado);

        // Actualizar la interfaz
        checkbox.getParent().revalidate();
        checkbox.getParent().repaint();
    }

    // Actualizar la interfaz después de agregar los paneles, para que no haya errores al mostrarse
    private void actualizarInterfaz() {
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }

    // Buscar los paneles de personal seleccionados
    private List<Component> buscarPersonalSeleccionados() {
        List<Component> panelesPersonal = new ArrayList<>();

        for (Component comp : panelContenedor.getComponents()) {
            if (comp instanceof JPanel jPanel) {
                if (isCheckboxSeleccionado(jPanel)) {
                    panelesPersonal.add(comp);
                }
            }
        }
        return panelesPersonal;
    }

    // Verificar si el checkbox está seleccionado en el panel
    private boolean isCheckboxSeleccionado(JPanel panel) {
        JCheckBox checkbox = obtenerCheckBoxEmpleado(panel);
        return checkbox != null && checkbox.isSelected();
    }

    // Mostrar paneles según el filtro ingresado
    public void filtrarPersonal() {
        String filtro = txtFiltroPersonal.getText().trim().toLowerCase(); // Obtener texto de búsqueda

        for (Component componente : panelContenedor.getComponents()) {
            if (componente instanceof JPanel panel) {
                JCheckBox checkBoxEmpleado = obtenerCheckBoxEmpleado(panel);

                if (checkBoxEmpleado != null) {
                    String nombreEmpleado = checkBoxEmpleado.getText().toLowerCase();
                    panel.setVisible(nombreEmpleado.contains(filtro));
                }
            }
        }
    }

    // Obtener el JCheckBox del panel
    private JCheckBox obtenerCheckBoxEmpleado(JPanel panel) {
        for (Component comp : panel.getComponents()) {
            if (comp instanceof JCheckBox jCheckBox) {
                return jCheckBox;
            }
        }
        return null;
    }

    // Registrar la asistencia de los empleados seleccionados
    private List<AsistenciaPersonalDTO> registrarAsistenciaPorPersonal() throws PresentacionException {
        List<Component> panelesPersonalSeleccionados = buscarPersonalSeleccionados();
        List<AsistenciaPersonalDTO> listaAsistenciaPersonal = new ArrayList<>();

        for (Component panel : panelesPersonalSeleccionados) {
            if (!(panel instanceof JPanel panelEmpleado)) {
                continue;
            }

            String nombre = null;
            LocalTime horaEntrada = null;
            LocalTime horaSalida = null;
            String notas = null;

            for (Component comp : panelEmpleado.getComponents()) {
                String nombreComponente = comp.getName();
                if (nombreComponente == null) {
                    continue;
                }

                switch (nombreComponente) {
                    case "checkbox" ->
                        nombre = ((JCheckBox) comp).getText();
                    case "timePickerEntrada" ->
                        horaEntrada = ((TimePicker) comp).getTime();
                    case "timePickerSalida" ->
                        horaSalida = ((TimePicker) comp).getTime();
                    case "textPaneNotas" ->
                        notas = ((JTextPane) comp).getText();
                }
            }

            // Validar horas y lanzar excepción si es necesario
            coordinadorNegocio.validarHoras(horaEntrada, horaSalida, nombre);

            // Agregar la asistencia del personal a la lista
            listaAsistenciaPersonal.add(new AsistenciaPersonalDTO(nombre, horaEntrada, horaSalida, notas));
        }

        return listaAsistenciaPersonal;
    }
 
    private void siguiente() {
        // Intentar registrar la bitacora
        try {
            coordinadorNegocio.registrarAsistencia(registrarAsistenciaPorPersonal());

            int opcion = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que desea registrar la bitácora? No podrá editarse después.",
                    "Confirmar registro", JOptionPane.YES_NO_OPTION);
            if (opcion != JOptionPane.YES_OPTION) {
                return;
            }

            coordinadorNegocio.registrarBitacora();
            JOptionPane.showMessageDialog(this, "Bitácora registrada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Regresar a ventana ObraSeleccionada
            this.dispose();
            coordinador.mostrarObraSeleccionada();
        } catch (PresentacionException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void atras() {
        this.dispose();
        coordinador.mostrarHerramientasYMaquinaria();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel nombreEmpresa;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel registrarAsistencia;
    private com.github.lgooddatepicker.components.TimePicker timePicker4;
    private com.github.lgooddatepicker.components.TimePicker timePicker5;
    private javax.swing.JTextField txtFiltroPersonal;
    // End of variables declaration//GEN-END:variables
}
